
////
This has been cut and moved to the main Swift/T Guides:
////

. Install prerequisites: You need MPI, Tcl, SWIG, ZSH, Ant, JDK, R, and the typical C/C++ compiler tools.  These may be installed using your system package manager, but be sure to install the development versions so that the compile-time headers, etc., are available.
. Install RInside using R's `install.packages()` (except on `osx-arm64`, see below):
+
----
$ R
> install.packages("RInside")
# Pick any CRAN mirror
* installing *source* package 'RInside' ...
using C++ compiler: ...
miscellaneous g++ commands...
...
* DONE (RInside)
----
. Download and unpack the Swift/T source:
+
----
$ wget http://swift-lang.github.io/swift-t-downloads/1.6/swift-t-1.6.3.tar.gz
$ tar xfz swift-t-1.6.3.tar.gz
$ cd swift-t-1.6.3
----
. Configure Swift/T by editing its settings file:
+
----
$ ./dev/build/init-settings.sh
$ run your editor on ./dev/build/swift-t-settings.sh
----
+
In +swift-t-settings.sh+, ensure that your `mpicc`, Tcl, Python, and R settings are correct.  The defaults usually work if the tools are in `PATH`.  Tcl should be the one in Anaconda.
. Run the installer with:
+
----
$ dev/build/build-swift-t.sh
----
. Add to `PATH`:
+
----
PATH=$PATH:/path/to/swift-t-install/stc/bin
----
. Test with:
+
----
$ swift-t -v
$ swift-t -E 'trace(42);'
----

==== R on `osx-arm64`

This new OS combination with Anaconda does not seem to support R with the RInside library for C++ integration.  You must install R from source.

. Install R dependencies bzip2, XZ, and PCRE2 and set the `-I` and `-L` flags via `CPPFLAGS` and `LDFLAGS` (details below)
. Download and unpack R:
+
----
$ wget https://cran.r-project.org/src/base/R-4/R-4.3.2.tar.gz
$ tar xfz R-4.3.2.tar.gz
$ cd R-4.3.2
----
. Configure and build R:
+
----
$ ./configure --config-cache           \
              --prefix=/home/path/to/R \
              --enable-R-shlib         \
              --disable-java           \
              --without-tcltk          \
              --without-cairo          \
              --without-jpeglib        \
              --without-libtiff        \
              --without-ICU            \
              --without-x
$ make
$ make install
----
. Install RInside via `install.packages()`
. Proceed with the installation using this R in `swift-t-settings.sh`

===== Install R dependencies

Your options here are:

* Anaconda
* Source builds
* Possibly Homebrew, etc.

NOTE: When performing builds from source, make sure that your compilers are compatible among the Anaconda/Python, R, Fortran, and MPI components.  Use `mpicc -show` to check the MPI compiler.

You may need to tell `mpicc` and `mpicxx` to set the compiler locations via:

----
$ export MPICH_CC=clang
$ export MPICH_CXX=clang++
----

For Anaconda, simply:

----
$ conda install bzip2 pcre2 xz gfortran
----

Make sure `xcrun` is installed via:

----
$ xcode-select --install
----

Then set the compiler paths for R `configure` to look in Anaconda and the SDK locations:
----
export CC=clang
export CXX=clang++

PY=/path/to/Anaconda
PATH=$PY/bin:$PATH

SDK=$( xcrun --show-sdk-path )

export CPPFLAGS="-I$PY/include -I$SDK/usr/include"
export LDFLAGS="-L$PY/lib -Wl,-rpath -Wl,$PY/lib "
       LDFLAGS+="-L$SDK/usr/lib -F$SDK/System/Library/Frameworks"
----

You can use `clang` / `clang++` from the system default location.
