IMPORTANT: #Highlights# below have in source TODOs.
[[uc1, Use Case 1 Tutorial - Simple Workflows with ABM]]
== #Simple# Workflows with ABM
// TODO: try to unify the voice used throughout

For a first demonstration ABM use case, we begin with an example of a Swift/T
parallel parameter sweep to explore the parameter space of a model.
This tutorial uses the project structure and files created from the
// TODO: Include link to project creator section.
EMEWS #<<_sweep_template,sweep template>>#, 
and that should be read before this.


=== Tutorial goals

* Run an ABM simulation using Repast in Swift/T
* Execute parallel parameters sweep of ABM simulation model 
* Implement parallel evaluation of the simulation results using Swift/T and R

=== Workflow Project Structure
The full source code for this tutorial use case can be accessed https://github.com/jozik/emews_next_gen_tutorial_tests/tree/main/code/uc1[here,window=UC1,pts="noopener,nofollow"].
// TODO: modify the structure and files to reflect the final uc1 version. Just run tree on completed version.
The completed workflow project has the following directory #structure and files#:
// NB: Generated using tree.
[source,text]
----
uc1
├── R
│   └── test
├── README.md
├── data
├── etc
│   └── emews_utils.sh
├── ext
│   └── emews
│       └── emews.swift
├── python
│   └── test
├── scripts
│   └── run_repast_uc1.sh
└── swift
    ├── cfgs
    │   └── sweep_workflow.cfg
    ├── run_sweep_workflow.sh
    └── sweep_workflow.swift
----

An initial version of the project was created using the EMEWS creator with the following command issued #here#:
// TODO: link to code directory in the repo? https://github.com/jozik/emews_next_gen_tutorial_tests/tree/main/code[here,window=UC1_code_directory,pts="noopener,nofollow"] or just say that it was issued in the code directory in this repo?
[source#uc1-creator,bash]
----
emewscreator -o uc1 sweep -c tutorial_cfgs/sweep.yaml
----


[NOTE]
====
For running this use case, an R enabled Swift/T installation is required.
See the http://swift-lang.github.io/swift-t/guide.html#build_r[Swift/T R Installation Guide, window=_blank,pts="noopener,nofollow"] for installation details.
====

=== JZombie: Repast simulation

The example model used here is an adaptation of the JZombies demonstration model distributed with Repast Simphony
(https://repast.github.io/docs/RepastJavaGettingStarted.pdf[Nick Collier and Michael North 2015,window=_blank,pts="noopener,nofollow"]). This is only an example model. Any simulation
or scientific application that can be
launched from the command line can be adapted to this paradigm. The fictional Zombies
versus Humans model is intended to illustrate that EMEWS, Swift/T, and Repast Simphony are domain agnostic.

==== Model details

The model has two kinds of agents, Zombies and Humans. Zombies chase the Humans,
seeking to infect them, while Humans attempt to evade Zombies. When a
Zombie is close enough to a Human, that Human is infected and becomes a
Zombie. During a typical run all the Humans will eventually become Zombies.
These agents are located in a two dimensional continuous
space where each agent has a x and y coordinate expressed as a floating point number
(and in a corresponding discrete grid with integer coordinates).
Movement is performed in the continuous space and translated into discrete grid coordinates.
The grid is used for neighborhood queries (e.g., given a Zombie’s location, where are the nearest Humans).
The model records the grid coordinate of each agent as well as a count of each agent type (Zombie or Human)
at each time step and writes this data to two files.
The initial number of Zombies and Humans is specified
by model input parameters zombie count and human count, and the distance a Zombie or Human can move at each
time step is specified by the parameters zombie step size and human step size.


=== Calling a Repast Simphony simulation from Swift/T


The full Swift/T script can be seen in https://github.com/jozik/emews_next_gen_tutorial_tests/blob/main/code/uc1/swift/uc1.swift#L1[uc1.swift,window=uc1.swift,pts="noopener,nofollow"].
The script consists of defining variables from environment variables and user input:
// Note: Using "java" for *.swift files

[source#variables,java]
----
string emews_root = getenv("EMEWS_PROJECT_ROOT");
string turbine_output = getenv("TURBINE_OUTPUT");

file model_sh = input(emews_root+"/scripts/run_repast_uc1.sh");
file upf = input(argv("f"));
----

and then defining four functions, one that calls the simulation, which is auto-generated by the EMEWS Creator <<uc1-creator,command>>:




[source#repast-app,java]
----
app (file out, file err) run_model(file shfile, string param_line, string instance)
{
    "bash" shfile param_line emews_root instance @stdout=out @stderr=err;
}
----

////
Example highlighting code block:
[source,ruby,highlight=2..5]
----
ORDERED_LIST_KEYWORDS = {
  'loweralpha' => 'a',
  'lowerroman' => 'i',
  'upperalpha' => 'A',
  'upperroman' => 'I',
}
----
////

two utility functions we create: 
[source,java]
----
app (void o) make_dir(string dirname) {
  "mkdir" "-p" dirname;
}

app (void o) run_prerequisites() {
  "cp" (emews_root+"/complete_model/MessageCenter.log4j.properties") turbine_output;
}
----

followed by the code that performs the sweep, auto-generated, with the `run_prerequisites` block uncommented:

[source,java]
----
main() {
  run_prerequisites() => {
    string upf_lines[] = file_lines(upf);
    foreach s,i in upf_lines {
      string instance = "%s/instance_%i/" % (turbine_output, i+1);
      make_dir(instance) => {
        file out <instance+"out.txt">;
        file err <instance+"err.txt">;
        (out,err) = run_model(model_sh, s, instance);
      }
    }
  }
}
----

Here we see how the EMEWS Creator allows for very minimal adjustment of the workflow code to adapt to specific use cases.

==== Calling the External Application

In order for Swift/T to call our external application (i.e., the Zombies model),
we define an
// TODO: connect to external_execution section in Swift/T tutorial
#<<_external_execution,app>># function.
(The Zombies model is written in Java which is not easily called via Tcl and thus an app function is the best
choice for integrating the model into a Swift script. See the Swift/T Tutorial for more details.) Repast Simphony provides command line compatible functionality
via an InstanceRunner class, for passing a set of parameters to a model and performing a single headless
run of the model using those parameters. Using the InstanceRunner main class, Repast Simphony models can be launched by other
control applications such as a bash, slurm, or Swift scripts.  We have wrapped the command line invocation of
Repast Simphony's InstanceRunner in a bash script https://github.com/jozik/emews_next_gen_tutorial_tests/blob/main/code/uc1/scripts/run_repast_uc1.sh#L1[run_repast_uc1.sh,window=run_repast_uc1.sh,pts="noopener,nofollow"]
 to ease command line usage.

Other non-Repast Simphony models or scientific applications with command line interfaces can be wrapped
and run similarly.


An annotated version of the Swift app function that calls Repast Simphony is shown <<repast-app,below>>.
Prior to the actual function definition, the environment variable
EMEWS_PROJECT_ROOT is accessed. This variable is used to define the project's top level
directory, relative to which other directories (e.g., the directory
that contains the Zombies model) are defined. The value of the TURBINE_OUTPUT
environment variable is also retrieved. This specifies the path to
a directory where Swift/T stores its log files and which we will use
as a parent directory for the working directories of our individual runs.
For more on these variables see the
// TODO: Include link to project creator section.
#<<swift_run_sweep_sh,discussion>># in the template tutorial.

[source#repast-app-annot,java]
.Repast Simphony App Function
----
app (file out, file err) run_model(file shfile, string param_line, string instance)  <1>
{
    "bash" shfile param_line emews_root instance @stdout=out @stderr=err;  <2>
}
----
<1> The app function definition begins. The function returns two files, one for standard output and one for standard error.
The function arguments are those required to run https://github.com/jozik/emews_next_gen_tutorial_tests/blob/main/code/uc1/scripts/run_repast_uc1.sh#L1[run_repast_uc1.sh,window=run_repast_uc1.sh,pts="noopener,nofollow"], that is,
the full path of the script, the parameters to run and the directory where the model run output should be written.
<2> The body of the function calls the bash interpreter passing it the name of the script file to execute and the other function
arguments as well as the project root, that is, `emews_root` directory.
`@stdout=out` and `@stderr=err` redirect stdout and stderr to the files out and err.
It should be easy to see how any model or application that can be run from the command line
and wrapped in a bash script can be called from Swift in this way.

==== Utility Functions
As mentioned above, the Swift script also contains two utility app functions.

[source#util-app-annot,java]
.Utility Functions
----
app (void o) make_dir(string dirname) { <1>
  "mkdir" "-p" dirname;
}

app (void o) run_prerequisites() {  <2>
  "cp" (emews_root+"/complete_model/MessageCenter.log4j.properties") turbine_output;
}
----
<1> `make_dir` simply calls the Unix `mkdir` command to create a specified directory
<2> `run_prerequisites` calls the unix `cp` command to copy a Repast Simphony logging configuration file into
the current working directory.

Both of these are used by the parameter sweeping part of the script.

=== Parameter Sweeping

The remainder of the Swift script performs a simple parameter sweep using the `run_model` app function to run the model.
The parameters over which we want to sweep are defined in an external file, the so-called unrolled parameter file (UPF),
where each row of the file contains a parameter set for an individual run. The script will read
these parameter sets and launch as many parallel runs as possible for a given process configuration,
passing each run an individual parameter set. The general script flow is as follows:

* Read the the list of parameters into a `file` object.
* Split the contents of the file into lines and store each as an array element.
* Iterate over the array in parallel, launching a model run
for each parameter set (i.e., array element) in the array, using
the `run_model` app function.

[source#sweep-annot,java]
.Parameters Sweep
----
string emews_root = getenv("EMEWS_PROJECT_ROOT");
string turbine_output = getenv("TURBINE_OUTPUT");

file model_sh = input(emews_root+"/scripts/run_repast_uc1.sh");  <1>
file upf = input(argv("f"));  <2>

main() {
  run_prerequisites() => {  <3>
    string upf_lines[] = file_lines(upf);  <4>
    foreach s,i in upf_lines {  <5>
      string instance = "%s/instance_%i/" % (turbine_output, i+1);
      make_dir(instance) => {  <6>
        file out <instance+"out.txt">;
        file err <instance+"err.txt">;  <7>
        (out,err) = run_model(model_sh, s, instance);  <8>
      }
    }
  }
}
----
<1> Initialize a Swift/T `file` variable with the location of the `run_repast_uc1.sh` script file. Note that the Swift/T `input`
function takes a path and returns a `file`.
<2> The path of the parameter file that contains
the parameter sets that will be passed as input to the Zombies model is defined, also as a `file` variable.
This line uses
the swift built-in function `argv` to parse command line arguments to the Swift script.
As indicated earlier, each line of this `upf` file contains an individual parameter set, that is,
the random_seed, zombie_count, human_count, zombie_step_size and human_step_size
for a single model run. The parameter set is passed as a single string
(e.g., random_seed = 14344, zombie_count = 10, ...)
to the Zombies model where it is parsed into the individual parameters.
<3> Script execution begins by calling the `run_prerequisites` app function.
In the absence of any data flow dependency, Swift statements will execute in parallel whenever possible.
However, in our case, the Repast Simphony logging configuration file must be in place before a Zombie model run begins.
The `=>` symbol enforces the required sequential execution:
the code on its left-hand side must complete execution before the code on the right-hand side begins execution.
<4> Read the `upf` file into an array of strings where each line of the file is an element in the array.
The built-in Swift `file_lines` function (requires import of files module at the top of https://github.com/jozik/emews_next_gen_tutorial_tests/blob/main/code/uc1/swift/uc1.swift#L3[uc1.swift,window=uc1.swift,pts="noopener,nofollow"])
is used to read the upf file into this array of strings.
<5> The `foreach` loop 
executes its loop iterations in parallel. In the `foreach` loop, the variable `s` is set to an
array element (that is, a single parameter set represented as a string) while the variable `i` is the index of that array element.
<6> Create an instance directory into which each model run will write its output. The `make_dir` app function
is used to create the directory. The `=>` keyword is again used to ensure that the directory is created before the actual model
run that uses that directory is performed.
<7> Create file objects into which the standard out and standard error streams are
redirected by the <<repast-app-annot,run_model>> #function#.
// TODO: Do we explain the <... + ...> syntax anywhere?
<8> Lastly the `run_model` app function that performs the Zombie model run is called with the required arguments.

This is a common pattern in EMEWS. Some collection of parameters is parsed into an array in which each element
is the set of parameters for an individual run. A foreach loop is then
used to iterate over the array, launching parallel model runs each with
their own parameters. In this way the number of model runs that can be
performed in parallel is limited only by hardware resources.

=== Results Analysis

In our initial script we have seen how to run multiple instances of the Zombies model in parallel, each with a different set of parameters.
Our next example builds on this by adding some post-run analysis that explores the effect of simulated step size on the final
number of humans. This analysis will be performed in R and executed within the Swift workflow.

The new script consists of the following steps:

* Read the the list of a parameters into a `file` object.
* Split the contents of the file into an array where each line of file is an array element.
* Iterate over the array in parallel, launching a model run
for each parameter set (i.e. array element) in the array, using
the repast app function.
* Get the final human count from each run using R, and add it to an array.
* Also using R, determine the maximum human counts.
* Get the parameters that produced those maximum human counts.
* Write those parameters to a file.

This example assumes an existing parameter file in which zombie_step_size and human_step_size are varied.
For each run of the model, that is, for each combination of parameters, the model records a count of
each agent type at each time step in an output file. As before the script will iterate through the
file performing as many runs as possible in parallel. However, an additional step that reads each output file and
determines the parameter combination or combinations that resulted in the most humans surviving at the
final time step has been added.

The full updated swift code is in https://github.com/jozik/emews_next_gen_tutorial_tests/blob/main/code/uc1/swift/uc1_R.swift#L1[uc1_R.swift,window=uc1_R.swift,pts="noopener,nofollow"].

The updated code includes embedded R code that can be invoked using Swift's `R` function:
[source,java]
----
import R;

string count_humans = ----
last.row <- tail(read.csv("%s/counts.csv"), 1)
res <- last.row["human_count"]
----;

string find_max =  ----
v <- c(%s)
res <- which(v == max(v))
----;
----

an expanded `foreach` loop:

[source,java]
----
string upf_lines[] = file_lines(upf);
string results[];
foreach s,i in upf_lines {
  string instance = "%s/instance_%i/" % (turbine_output, i+1);
  make_dir(instance) => {
    file out <instance+"out.txt">;
    file err <instance+"err.txt">;
    (out,err) = run_model(model_sh, s, instance) => {
      string code = count_humans % instance;
      results[i] = R(code, "toString(res)");
    }
  }
}
----

and calls to the post processing code:
[source,java]
----
string results_str = string_join(results, ",");
string code = find_max % results_str;
string maxs = R(code, "toString(res)");
string max_idxs[] = split(maxs, ",");
string best_params[];
foreach s, i in max_idxs {
  int idx = toint(trim(s));
  best_params[i] = upf_lines[idx - 1];
}
file best_out <emews_root + "/output/best_parameters.txt"> =
  write(string_join(best_params, "\n"));
----

We describe this in two parts. The first describes the changes to the `foreach` loop to gather the output and the
second describes how that output is analyzed to determine the "best" parameter combination.


==== Gathering the Results

[source#enhanced-foreach-annot,java]
.Enhanced foreach loop
----
import R;  <1>

string count_humans = ----  <2>
last.row <- tail(read.csv("%s/counts.csv"), 1)  <3>
res <- last.row["human_count"]  <4>
----;

...

string upf_lines[] = file_lines(upf);
string results[];  <5>
foreach s,i in upf_lines {
  string instance = "%s/instance_%i/" % (turbine_output, i+1);
  make_dir(instance) => {
    file out <instance+"out.txt">;
    file err <instance+"err.txt">;
    (out,err) = run_model(model_sh, s, instance) => {
      string code = count_humans % instance;  <6>
      results[i] = R(code, "toString(res)");  <7>
    }
  }
}
----
<1> To use Swift/T's support for the R language, the R module is imported.
<2> A multiline R script, delineated by `----`, is assigned to the `count_humans` string variable.
<3> The string contains a template character, "%s", which is replaced with the actual directory (described below) in which the output file (counts.csv) is written.
The R script reads the CSV file produced by a model run into a data frame.
<4> The last row of the data frame is accessed and the value of the `human_count` column in that row is
assigned to a `res` variable.
<5> A `results` array is initialized.
<6> The `run_model` call is followed by the execution of the R script. First, the template substitution is performed with the directory for the current run, using the "%" format Swift operator.
<7> R code can be run using Swift's `R` function. `R` takes two arguments, the R code to run,
and an additional R statement that generates the desired return value of the R
code as a string. The return statement is typically, as seen here, something like `"toString(res)"`
where R's `toString` function is passed a variable that contains what
you want to return from the R script. In this case, the `res` variable contains the number of surviving humans.
This string is then placed in the `results` array at the ith index.

==== Finding the Best Parameters

The final workflow steps are to determine which runs yielded the maximum
number of humans and write out the parameters for those runs. The core idea here is
that we find the indices of the elements in the
results array that contain the maximum human counts and use those indices
to retrieve the parameters from the parameters array.

[source#find-best-param-annot,java]
.Finding the best parameter
----
string find_max =  ----
v <- c(%s)  <1>
res <- which(v == max(v))  <2>
----;

...

string results_str = string_join(results, ",");  <3>
string code = find_max % results_str;  <4>
string maxs = R(code, "toString(res)");  <5>
string max_idxs[] = split(maxs, ",");  <6>
string best_params[];
foreach s, i in max_idxs {  <7>
  int idx = toint(trim(s));  <8>
  best_params[i] = upf_lines[idx - 1];  <9>
}
file best_out <emews_root + "/output/best_parameters.txt"> =
  write(string_join(best_params, "\n"));  <10>
----
<1> The R script takes in the results from all of the model runs, as a comma separated string of values, through the "%s" template character (assigned below).
<2> The (1-based) indices of the maximum values are found and stored in the `res` variable.
<3> Swift's `string_join` function (requiring importing the string module) is used to join all the elements of the results array,
i.e., all the final human counts, into a comma separated string.
<4> The comma separated string is assigned to the template character in the `find_max` R script and assigned to the `code` string.
<5> As before, Swift's R function is called with the `code` string to yield the max indices.
<6> This string is split into a `max_idxs` array using Swift's `split` function.
The `split` function takes two arguments, the string to split and the string
to split on, and returns an array of strings.
<7> The foreach loop iterates through `max_idxs` array.
<8> The string representation of each number is converted to an integer.
<9> The corresponding parameter string is retrieved from the `upf_lines` array, and
is added to the `best_params` array.
Given that the value in `results`[i] (from which the max indices are derived) is produced from the parameter combination in
`upf_lines`[i], the index of the maximum value or values in the `max_idxs` array is the index of the best parameter combination or combinations.
Note that we subtract one from `idx` because R indices start at 1 while Swift's start at 0.
<10> The final step is to write the best parameters to a file using Swift's `write` function.


=== Running the Swift Script
Swift scripts are typically launched using a shell script. This allows
one to export useful values as environment variables and to properly
configure the Swift workflow to be run on HPC resources.
The EMEWS Creator will automatically create such a shell script. The shell script for running
our simple workflow can be see in https://github.com/jozik/emews_next_gen_tutorial_tests/blob/main/code/uc1/swift/run_uc1.sh#L1[run_uc1.sh,window=run_uc1.sh,pts="noopener,nofollow"].

[source#run-uc1-front-annot,bash]
.run_uc1.sh selected parts
----
if [ "$#" -ne 2 ]; then  <1>
  script_name=$(basename $0)
  echo "Usage: ${script_name} exp_id cfg_file"
  exit 1
fi

# Uncomment to turn on swift/t logging. Can also set TURBINE_LOG,
# TURBINE_DEBUG, and ADLB_DEBUG to 0 to turn off logging
# export TURBINE_LOG=1 TURBINE_DEBUG=1 ADLB_DEBUG=1  <2>
export EMEWS_PROJECT_ROOT=$( cd $( dirname $0 )/.. ; /bin/pwd )  <3>

... 

export EXPID=$1
export TURBINE_OUTPUT=$EMEWS_PROJECT_ROOT/experiments/$EXPID  <4>
check_directory_exists

CFG_FILE=$2
source $CFG_FILE  <5>

echo "--------------------------"
echo "WALLTIME:              $CFG_WALLTIME"
echo "PROCS:                 $CFG_PROCS"
echo "PPN:                   $CFG_PPN"
echo "QUEUE:                 $CFG_QUEUE"
echo "PROJECT:               $CFG_PROJECT"
echo "UPF FILE:              $CFG_UPF"
echo "--------------------------"

export PROCS=$CFG_PROCS
export QUEUE=$CFG_QUEUE
export PROJECT=$CFG_PROJECT
export WALLTIME=$CFG_WALLTIME
export PPN=$CFG_PPN
...
# Copies UPF file to experiment directory
U_UPF_FILE=$EMEWS_PROJECT_ROOT/$CFG_UPF  
UPF_FILE=$TURBINE_OUTPUT/upf.txt
cp $U_UPF_FILE $UPF_FILE  <6>

CMD_LINE_ARGS="$* -f=$UPF_FILE "  <7>
...

SWIFT_FILE=uc1.swift  <8>
swift-t -n $PROCS $MACHINE -p \
    -I $EMEWS_EXT -r $EMEWS_EXT \
    -e TURBINE_MPI_THREAD \
    -e TURBINE_OUTPUT \
    -e EMEWS_PROJECT_ROOT \
    $EMEWS_PROJECT_ROOT/swift/$SWIFT_FILE \
    $CMD_LINE_ARGS
----
<1> run_uc1.sh takes 2 required arguments (exp_id and cfg_file).
The first is an experiment id (e.g., "experiment_1"), which is used to define a directory (TURBINE_OUTPUT, defined below)
into which per workflow output can be written. Swift will also write its own
log files into this directory as the workflow executes.
The second required argument is the workflow configuration file. EMEWS Creator will have auto-generated
a configuration file based on the information provided to it, and can be seen in https://github.com/jozik/emews_next_gen_tutorial_tests/blob/main/code/uc1/swift/cfgs/uc1.cfg#L1[uc1.cfg,window=uc1.cfg,pts="noopener,nofollow"].
<2> Additional logging, including debugging logs, can be enabled by uncommenting.
<3> EMEWS_PROJECT_ROOT is defined and exported here. The workflow launch script assumes the canonical EMEWS directory structure, where
the so-called EMEWS project root directory contains other directories
such as a `swift` directory in which the swift scripts are
located.
<4> The TURBINE_OUTPUT directory is defined, using the EMEWS_PROJECT_ROOT and EXPID environment variables.
<5> The configuration file is sourced, bringing in the specific CFG_X environment variables defined there.
These include environment variables that are required for
cluster execution such as queue name (`QUEUE`), project name (`PROJECT`), requested walltime (`WALLTIME`),
processes per node (`PPN`), and so forth. Any additional environment variables can be included here
and optionally also provided through the configuration file mechanism.
<6> The utilized unrolled parameter file is copied to the TURBINE_OUTPUT directory to document
the details of the workflow and also to prevent any inadvertent overwriting between script submission and the job run.
<7> The command line arguments provided to the Swift script are constructed. Here the "-f=" argument points to the unrolled parameter file.
<8> The final lines run the swift script by
calling `swift-t` with Swift specific, e.g., "-n" specifies the total number of processes on which to run,
and script specific arguments, here the CMD_LINE_ARGS defined above.
Additional help for the arguments to `swift-t` can be seen by running
`swift-t -h`. More information on the shell script used to
launch the Swift/T workflow can be seen in the #EMEWS Creator tutorial#.
// TODO: Include link to project creator section.
